# Generated by Django 3.2.5 on 2021-07-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
